//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MINHAS_FINANCAS_ADMIN
{
    using System;
    using System.Collections.Generic;
    
    public partial class Renda
    {
        public int id { get; set; }
        public string descricao { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string dataRecebimento { get; set; }
        public Nullable<int> id_usuario { get; set; }
    
        public virtual Renda Renda1 { get; set; }
        public virtual Renda Renda2 { get; set; }
    }
}
